[package]
name = "cargo-tags"
version = "0.1.0"
authors = [ "Clark Gaebel <cgaebel@mozilla.com>" ]
license = "MIT"

[dependencies]

[dependencies.cargo]
git = "https://github.com/rust-lang/cargo"

[[bin]]
name = "cargo-tags"
test = false
doc = true
